module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  verbose: true,
  clearMocks: true,
  restoreMocks: true,
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  transform: {
    '^.+\\.tsx?$': ['ts-jest', {
      tsconfig: 'tsconfig.json',
    }],
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  collectCoverage: false,
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'json', 'html'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.types.ts',
    '!src/**/*.validation.ts',
    '!src/**/*.route.ts',
    '!src/**/*.routes.ts',
    '!src/**/*.controller.ts',
    '!src/**/*.constants.ts',
    '!src/server.ts',
    '!src/app.ts',
    '!src/config/**',
    '!src/docs/**',
    '!src/logs/**',
    '!src/tests/**',
    '!src/utils/prisma.ts',
    '!src/utils/stripe.ts',
    '!src/utils/file.utils.ts',
    '!src/utils/queryBuilder.ts',
    '!src/queues/**',
    '!src/services/**',
  ],
  coverageThreshold: {
    './src/modules/orders/order.utils.ts': {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    './src/modules/product/product.utils.ts': {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    './src/modules/reservation/reservation.utils.ts': {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    './src/modules/payment/payment.utils.ts': {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    './src/utils/testimonialSpamCheck.ts': {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    './src/utils/slugify.ts': {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    './src/utils/formatters.ts': {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    './src/security/suspicious-request.detector.ts': {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
};
