/**
 * Centralized Constants for the Emails Module
 */
export const EMAILS_CONSTANTS = {
  TEMPLATES: {
    TEST_EMAIL: 'TEST_EMAIL',
    WELCOME_EMAIL: 'WELCOME_EMAIL',
    RESET_PASSWORD: 'RESET_PASSWORD',
    ORDER_CONFIRMATION: 'ORDER_CONFIRMATION',
    RESERVATION_CONFIRMATION: 'RESERVATION_CONFIRMATION',
    REFUND_NOTIFICATION: 'REFUND_NOTIFICATION',
    ADMIN_NOTIFICATION: 'ADMIN_NOTIFICATION',
  },
  DEFAULT_FROM: 'Crusty\'s Express <noreply@crustys.com>',
  DEFAULT_REPLY_TO: 'support@crustys.com',
};
